[package]
name = "kaspa-db-filler-ng"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.5", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
bigdecimal = "0.4"
hex = "0.4.3"
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
