[package]
name = "simply-kaspa-cli"
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true

[features]
default = []

[lib]
name = "simply_kaspa_cli"
crate-type = ["cdylib", "lib"]

[dependencies]
clap.workspace = true
